### ISSUE TITLE
Docker Compose, check that mongo-db is up

### ISSUE THREAD

**Issue by mkuendig** [DeviaVir/zenbot#139]
Please change Docker-Compose file to include health-checks and start dependencies:

```
version: "2.1"
services:
  server:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3013:3013"
    links:
      - mongodb
      - reducer
      - btc-usd
      - eth-usd # Uncomment for `eth-usd` support (also uncomment container below)
      #- eth-btc # Uncomment for `eth-btc` support (also uncomment container below)
    depends_on:
      mongodb:
        condition: service_healthy
    command: ./server.sh

  reducer:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - mongodb
    depends_on:
      mongodb:
        condition: service_healthy
    command: ./reducer.sh

  btc-usd:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - mongodb
    depends_on:
      mongodb:
        condition: service_healthy
    command: ./run-btc-usd.sh

  ## Uncomment for `eth-usd` support
  eth-usd:
    build: .
    volumes:
       - .:/app
       - /app/node_modules
    links:
       - mongodb
    depends_on:
      mongodb:
        condition: service_healthy
    command: ./run-eth-usd.sh
  ### /Uncomment for `eth-usd` support

  ### Uncomment for `eth-btc` support
  #eth-btc:
  #  build: .
  #  volumes:
  #    - .:/app
  #    - /app/node_modules
  #  links:
  #     - mongodb
  #  depends_on:
  #    mongodb:
  #      condition: service_healthy
  #  command: ./run-eth-btc.sh
  ### /Uncomment for `eth-btc` support

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes_from:
      - mongodb-data
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/zenbrain --quiet
      interval: 5s
      timeout: 5s
      retries: 12
    command: mongod --smallfiles

  mongodb-data:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    command: "true"
```
