### ISSUE TITLE
How i connet more Accounts

### ISSUE THREAD

**Issue by Ultrahoschie** [DeviaVir/zenbot#541]
Hey...

How i connect more than one Accounts of Bitfinex?

Need i installed a new Instance of Zenbot?

Thx

**Comment by Froelund** [comment]
I would just spin up multiple zenbot docker containers.

**Comment by nibzo1** [comment]
Use [`PM2` ](http://pm2.keymetrics.io/) process manager
 
You can then create a config file like this and call it anything and give it an extentions `.yaml`
so `botz.yaml`

Create as many of these bot configs you like in the file 

```yaml
  - script   : ./zenbot.js
    name     : 'bittrex.QTUM-BTC.RSI'
    watch  : true
    restart_delay : 30000
    args    : 'trade bittrex.QTUM-BTC --strategy=rsi --period=1m --min_periods=52 --rsi_periods=14 --oversold_rsi=28 --conf=config1.js'
```

you should be able to override any of the config options with the args field

Specify a different config file  with `--conf=config1.js`
